spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 7

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: alsdn0508!
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 600
    store-type: jdbc
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION


  security:
    user:
      name: user
      password: 1111
minu:
  jwt-key: "LM6e6xmkbje1qT4vd1Tj+ewsslsLzEB3qP4tgtOd9Uk="

