spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 7

  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: alsdn0508!
    driver-class-name: com.mysql.cj.jdbc.Driver

